export const SET_CURRENT = "SET_CURRENT";
export const SELECT_PACKAGE = "SELECT_PACKAGE";

export const POLICY_METADATA_POST_SUCCESS = 'POLICY_METADATA_POST_SUCCESS';
export const POLICY_METADATA_POST_FAILURE = 'POLICY_METADATA_POST_FAILURE';