export const SET_CURRENT = "SET_CURRENT";
export const SELECT_PACKAGE = "SELECT_PACKAGE";
export const SET_LICENSE = "SET_LICENSE";

export const REQUEST_ACCOUNT = "REQUEST_ACCOUNT";
export const REQUEST_ACCOUNT_SUCCESS = "REQUEST_ACCOUNT_SUCCESS";
export const REQUEST_ACCOUNT_FAILURE = "REQUEST_ACCOUNT_FAILURE";

export const REQUEST_CONTACTS = "REQUEST_CONTACTS";
export const REQUEST_CONTACTS_SUCCESS = "REQUEST_CONTACTS_SUCCESS";
export const REQUEST_CONTACTS_FAILURE = "REQUEST_CONTACTS_FAILURE";

export const REQUEST_ACCOUNT_UPDATE = "REQUEST_ACCOUNT_UPDATE";
export const REQUEST_ACCOUNT_UPDATE_SUCCESS = "REQUEST_ACCOUNT_UPDATE_SUCCESS";
export const REQUEST_ACCOUNT_UPDATE_FAILURE = "REQUEST_ACCOUNT_UPDATE_FAILURE";

export const REQUEST_MESSAGE_UPDATE = "REQUEST_MESSAGE_UPDATE";
export const REQUEST_ACCOUNT_MESSAGE_SUCCESS = "REQUEST_MESSAGE_UPDATE_SUCCESS";
export const REQUEST_ACCOUNT_MESSAGE_FAILURE = "REQUEST_MESSAGE_UPDATE_FAILURE";


export const REQUEST_GBB_UPDATE = "REQUEST_GBB_UPDATE";
export const REQUEST_GBB_SUCCESS = "REQUEST_GBB_SUCCESS";
export const REQUEST_GBB_FAILURE = "REQUEST_GBB_FAILURE";