export const SET_CURRENT = "SET_CURRENT";
export const SELECT_PACKAGE = "SELECT_PACKAGE";

export const REQUEST_ACCOUNT = "REQUEST_ACCOUNT";
export const REQUEST_ACCOUNT_SUCCESS = "REQUEST_ACCOUNT_SUCCESS";
export const REQUEST_ACCOUNT_FAILURE = "REQUEST_ACCOUNT_FAILURE";